# Generated by Django 2.1.1 on 2018-10-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_limits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('update_time', models.BigIntegerField()),
                ('channel', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='answer',
            new_name='answers',
        ),
        migrations.DeleteModel(
            name='time_limit',
        ),
    ]
