# Generated by Django 2.1.1 on 2018-10-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20181015_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='catalog_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo_url',
            field=models.ImageField(max_length=255, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo_url',
            field=models.ImageField(max_length=255, upload_to='images'),
        ),
    ]
