# Generated by Django 2.1.1 on 2018-10-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20181015_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo_url',
            field=models.ImageField(max_length=255, upload_to='photo/static/images'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo_url',
            field=models.ImageField(max_length=255, upload_to='photo/static/images'),
        ),
    ]
