# Generated by Django 2.1.1 on 2018-10-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20181015_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='mini_url',
            field=models.ImageField(max_length=255, null=True, upload_to='static/images'),
        ),
    ]
