# Generated by Django 2.1.1 on 2018-10-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_auto_20181015_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
