# Generated by Django 2.1.1 on 2018-10-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_photos_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
