# Generated by Django 2.1.1 on 2018-12-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20181017_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='mini_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('poetry_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mini_nuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=30)),
                ('gender', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('type', models.IntegerField()),
                ('passwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mini_poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('dubbing', models.CharField(max_length=50)),
                ('dubbing_1', models.CharField(max_length=50)),
                ('dubbing_2', models.CharField(max_length=50)),
                ('edit', models.IntegerField()),
                ('created_time', models.CharField(max_length=20)),
            ],
        ),
    ]
