# Generated by Django 2.1.1 on 2018-12-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_mini_history_mini_nuser_mini_poetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mini_nuser',
            name='token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
