# Generated by Django 2.1.1 on 2018-12-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_auto_20181201_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mini_nuser',
            name='token',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
