# Generated by Django 2.1.1 on 2018-12-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_auto_20181201_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mini_nuser',
            name='passwd',
            field=models.CharField(max_length=32),
        ),
    ]
