# Generated by Django 2.1.1 on 2018-12-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_auto_20181201_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mini_nuser',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mini_nuser',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mini_nuser',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mini_nuser',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
